### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by HoplaGeiss** [polo-language/bin-packer#1]
Hi, that's the only node.js 1D bin-packing library I found.
Could you please tell me if the algorithm used in 'firstFitDecreasing' is the most optimized?
I thought that to solve a NP problem you had to compute for a lot longer than this does.

**Comment by polo-language** [comment]
If by most optimized you mean that first fit decreasing is guaranteed to use the least number of bins for any given input, then the answer is no. All of the algorithms provided so far are approximation algorithms. But as you've noticed, they're fairly efficient. Unless you have a scientific application, it's likely that these are good enough. Do you need an exact solution?

**Comment by polo-language** [comment]
@HoplaGeiss The exact algorithm "bin completion" is now available on npm in version 1.5.0. If you don't need an exact solution, "best fit decreasing" is the one I'd recommend in most situations.
