### ISSUE TITLE
Have you considered adding "least" or "limited" repacking?

### ISSUE THREAD

**Issue by caboosesw** [polo-language/bin-packer#2]
I have a need and am willing to compensate someone who can implement this

We have a situation where we have existing packed "bins" ... but then we may receive larger "bins" and want to reshuffle everything with the least movement.

**Comment by polo-language** [comment]
Sounds interesting. Let's connect over email and discuss your use-case.

**Comment by caboosesw** [comment]
@polo-language I couldn't find your email anywhere.  Email me on bsmith@linqservices.com and then maybe remove this issue?
