### ISSUE TITLE
unpacked - when will this be used?

### ISSUE THREAD

**Issue by yuklai** [polo-language/bin-packer#5]
The result returned by the algorithm has an `unpacked` array. What is the high-level for when it will be returned?

**Comment by polo-language** [comment]
Each algorithm returns an object, and the bins are arrays of whatever objects you're packing. Quoted from the README:

> Each algorithm returns an object with the following keys:
> 
> - `bins:` An array of arrays, each containing elements with total size less than or equal to capacity.
> - `oversized`: An array containing any elements which on their own have a size greater than capacity.
> 

My understanding of [array unpacking](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#unpacking_properties_from_objects_passed_as_a_function_parameter) is that it is synonymous with destructuring: a **syntax** that enables extracting values from objects. It is not a feature of any specific object... So I don't know what you mean by the "result ... has an unpacked array".
